apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentinel-api
  template:
    metadata:
      labels:
        app: sentinel-api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/sentinel-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: sentinel
            - name: POSTGRES_USER
              value: sentinel
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-api
spec:
  selector:
    app: sentinel-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
